[package]
name = "mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { workspace = true }
serde = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
